version: '{build}'

branches:
  only:
  - master

image:
- Visual Studio 2017

configuration:
- Debug
- Release

environment:
  TOOLSET: v141
  ToolsVersion: 15.0
  VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat'
  
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      PLATFORM: x64
      ARCHITECTURE: x86_amd64
      GENERATOR: Visual Studio 15 2017 Win64
      CMAKE_DEPENDENCIES_DIR: Depends_WIN64
      CMAKE_SOLUTION_DIR: Win64
install:
  - cd ..
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - mkdir build && cd build
  - cmake .. -G "%GENERATOR%" -T %TOOLSET% -DCMAKE_CONFIGURATION_TYPES:STRING="%configuration%" -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_VS_INCLUDE_INSTALL_TO_DEFAULT_BUILD=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF
  - cmake --build . --config %configuration%
  - set glfw3_DIR=%cd%\src
  - echo "glfw3 done!"
  - cd .. && cd ..
  - git clone https://github.com/Enziferum/robot2D_ext.git
  - cd robot2D_ext
  - mkdir build && cd build
  - cmake .. -G "%GENERATOR%" -T %TOOLSET% -DCMAKE_CONFIGURATION_TYPES:STRING="%configuration%" -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_VS_INCLUDE_INSTALL_TO_DEFAULT_BUILD=ON
  - cmake --build . --config %configuration%
  - set robot2D_ext_DIR=%cd%\src
  - echo "robot2D_ext done!"
  - cd .. && cd ..
  - git clone https://github.com/gabime/spdlog.git
  - cd spdlog
  - mkdir build && cd build
  - cmake .. -G "%GENERATOR%" -T %TOOLSET% -DCMAKE_CONFIGURATION_TYPES:STRING="%configuration%" -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_VS_INCLUDE_INSTALL_TO_DEFAULT_BUILD=ON
  - cmake --build . --config %configuration%
  - set spdlog_DIR=%cd%\src
  - echo "spdlog done!"
  - cd .. && cd ..
  - cd robot2d

build_script:
- echo "Platform '%PLATFORM%'"
- echo "Generator '%GENERATOR%'"
- echo "Toolset '%TOOLSET%'"
- echo "ToolsetVersion '%ToolsVersion%'"
- echo "Configuration '%configuration%'"
- echo "Dependencies '%CMAKE_DEPENDENCIES_DIR%'"
- echo "Solution '%CMAKE_SOLUTION_DIR%'"
- call "%VCVARSALL%" %ARCHITECTURE%
- cmake --version
- mkdir build_cmake
- cd build_cmake
- cmake .. -G "%GENERATOR%" -T %TOOLSET% -DCMAKE_CONFIGURATION_TYPES:STRING="%configuration%" -DCMAKE_BUILD_TYPE=%configuration%
- cmake --build . --config %configuration%
- echo "Complete!"
