function(print_diagnostic)
    message("Diagnostics:")
    message("-----------------------------------------------")
    list(APPEND CMAKE_MESSAGE_INDENT "  -- ")
    message("CMake version: ${CMAKE_VERSION}")
    message("C++ compiler: ${CMAKE_CXX_COMPILER}")
    message("C++ standard: ${CMAKE_CXX_STANDARD}")
    list(POP_BACK CMAKE_MESSAGE_INDENT)
    message("-----------------------------------------------")
endfunction()
