name: CMake

on:
  pull_request:
    types: [opened, edited]

permissions: write-all

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install cpplint
        run: python3 -m pip install cpplint

      - name: Create linter folder
        run: mkdir ${{github.workspace}}/linter

      - name: Lint
        run: python3 -m cpplint --recursive --output=junit ${{github.workspace}}/engine 2> ${{github.workspace}}/linter/output.xml
        continue-on-error: true

      - name: Download dependencies
        run: python3 ${{github.workspace}}/scripts/install_deps.py

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Engine Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
            name: assets-for-download
            path: ${{github.workspace}}/linter
