name: Engine Build

on:
  push:
  pull_request:
    types: [opened, edited, reopened]

permissions: write-all

env:
  BUILD_TYPE: Release

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install cpplint
        run: python3 -m pip install cpplint

      - name: Create linter folder
        run: mkdir ${{github.workspace}}/linter

      - name: Lint
        run: python3 -m cpplint --recursive --output=junit ${{github.workspace}}/engine 2> ${{github.workspace}}/linter/output.xml
        continue-on-error: true

      - name: Download dependencies
        run: python3 ${{github.workspace}}/scripts/install_deps.py

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_EDITOR=OFF 

      - name: Engine Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Run Tests
        run: ctest test --output-junit engine_tests.xml --output-on-failure --test-dir ${{github.workspace}}/build/tests
      
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Engine Tests            # Name of the check run which will be created
          path: build/tests/*.xml    # Path to test results
          reporter: jest-junit        # Format of test results   	

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
            name: linux-assets
            path: ${{github.workspace}}/linter
